export {
  extractContactResult,
  extractContactsListResponse,
  getContactBadgeLabel,
  getContactDisplayName,
  getContactFormType,
  getContactSubtitle,
  mapBackendTypeToFrontendType,
  mapContactDataToApiPayload,
  mapContactToFormData,
  mapFrontendTypeToBackendType,
  normalizeContact,
  normalizeContactFormData,
  normalizeContactResult,
} from "./normalize-contact"
